targets:
  $default:
    builders:
      entity_generator:
        enabled: true

builders:
  generators:
    target: ":generators"
    import: "package:entity_generator/src/builder.dart"
    builder_factories: ["generateEntityBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
