#https://github.com/dart-lang/build/blob/master/build_config/README.md
#https://github.com/dart-lang/build/blob/master/docs/faq.md

targets:
  $default:
    builders:
      generators:generate_model_builder:
        enabled: true
        generate_for:
          - lib/**/*_entity.dart

builders:
  generators:generate_model_builder:
    import: "package:generators/src/builder.dart"
    builder_factories: [ "generateModelBuilder" ]
    # Extension should match the partId from builder.dart
    build_extensions: { ".dart": [ "test.dart" ] }
    auto_apply: dependents
    build_to: source
