targets:
  $default:
    builders:
      entity_generator:
        enabled: true
        generate_for:
          - "**/**entity.dart"

builders:
  generators:
    target: ":generators"
    import: "package:generators/src/builder.dart"
    builder_factories: [ "generateModelBuilder" ]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
